### ISSUE TITLE
This crate can run on wasm32 with a little modification.

### ISSUE THREAD

**Issue by warycat** [innoave/genevo#16]
I wrote a traveling salesman problem in rust and build it with wasm bindgen.

1. rayon::join doesn't work on wasm32, so I limit the population under 50.
1. time::get_time is unimplemented!. so I stub the time crate return value with 0. 

demo https://warycat.github.io/ga_wasm/
src https://github.com/warycat/ga_wasm

Thank you for making this awesome crate.

**Comment by ravicious** [comment]
I wasn't able to run any of the v0.5.0 examples in the browser, even with population size reduced to 40. The knapsack example doesn't even compile (IIRC), and running the others results in the following error:

```
panicked at 'could not initialize thread_rng: getrandom: this target is not supported', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.7.3/src/rngs/thread.rs:65:17

```

wasm-bindgen 0.2.63,  Rust 1.54.

**Comment by ravicious** [comment]
Thanks for the examples @warycat and @Bauxitedev. I was able to run the queens and the monkeys examples from v0.5.0 with the following modifications:

1. In `Cargo.toml` I added this to dependencies:

```toml
rand = { version = "0.7.3", features = ["wasm-bindgen"] }

[dependencies.chrono]
version = "0.4"
features = ["wasmbind"]
```

2. I reduced the population size to 40 for the queens example and 48 for the monkeys example (48 will probably work in both cases).

I used wasm-bindgen 0.2.63 and Rust 1.54 with the default wasm-pack 0.10.0 template.

Later I might check if the examples work with a bigger population after adding [wasm-bindgen-rayon](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon). [The caveats page](https://rustwasm.github.io/wasm-bindgen/examples/raytrace.html#caveats) sounds rather scary and I don't need my algorithm to perform well, yet.

**Comment by haraldmaida** [comment]
Thank you all for the feedback and input. I think I finally managed to add support for wasm32 targets to genevo. Starting with version 0.7.0 there is the crate feature `wasm-bindgen` that enables the support wasm32. Note that I disabled rayon (and multithreading) for wasm32 targets.

I modified the great example from @warycat to test if it really works. You can check out the modified example using genevo 0.7.0 here: [https://github.com/haraldmaida/ga_wasm](https://github.com/haraldmaida/ga_wasm)

**Comment by ravicious** [comment]
That’s fantastic news! Thank you very much!

I think I might try to see anyway if the previous version of genevo works with rayon if you use[ wasm-bindgen-rayon](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon).

**Comment by ravicious** [comment]
Ok, I tried to make 0.5.0 run with wasm-bindgen-rayon, but I ran into problems straight away:

* wasm-bindgen-rayon uses Module Workers which [doesn't work in all browsers](https://caniuse.com/mdn-api_worker_worker_ecmascript_modules). [The polyfill](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon#usage-without-bundlers) recommended in the readme [doesn't seem to work either](https://gist.github.com/developit/220246bc99044af74a6680ce13284f59#gistcomment-3957882).
* Even if the polyfill worked or you didn't care about people using Firefox, then you'd need to make [feature detection](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon#feature-detection) because not all browsers support WebAssembly threads.
* To make use of those threads, you need to enable [cross-origin isolation policies](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon#setting-up), which AFAIK isn't possible on GitHub Pages yet (which is what I'm using for my project).

At this point I'll just upgrade to 0.7.0 instead. ;)
